print ('\n'*3)
print ('----------------')
print ('First Python Program')
print ("---------------")
print ('\n')
name=input ('what is your name:')
print ('\n'*3)
print ('Hello', name)
print ('\n')
print ('Welcome to Python Programming')
print ('\n'*2)
